// hydra `osc` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: frequency (60.0), sync (0.1), offset (0.0)

uniform float time;          // -> absTime.seconds
uniform float uvmode;        // -> Pipeline page, mode
uniform float seamless;      // -> Pipeline page, seamless
uniform float seamwidth;     // -> Pipeline page, seam width
uniform float frequency;
uniform float sync;
uniform float offset;

#define COORD_IN 0

#define SEAMLESS_SNAP

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 osc(vec2 _st, float frequency, float sync, float offset) {
   vec2 st = _st;
   float r = sin((st.x-offset/frequency+time*sync)*frequency)*0.5  + 0.5;
   float g = sin((st.x+time*sync)*frequency)*0.5 + 0.5;
   float b = sin((st.x+offset/frequency+time*sync)*frequency)*0.5  + 0.5;
   return vec4(r, g, b, 1.0);
}

float _snap(float f) {
   if (seamless < 1.5 || uvmode > 0.5) return f;
   float k = max(1.0, floor(abs(f) / 6.283185307 + 0.5));
   return (f < 0.0 ? -k : k) * 6.283185307;
}

vec4 _src(vec2 st) {
   return osc(st, _snap(frequency), sync, offset);
}

vec4 _seamless(vec2 st) {
   vec4 c00 = _src(st);
   vec2 w = smoothstep(1.0 - max(seamwidth, 0.001), 1.0, abs(st * 2.0 - 1.0));
   if (w.x + w.y == 0.0) return c00;           // inside the band: plain hydra
   vec2 sh = fract(st + 0.5);
   vec4 c10 = _src(vec2(sh.x, st.y));
   vec4 c01 = _src(vec2(st.x, sh.y));
   vec4 c11 = _src(sh);
   vec4 a = vec4((1.0 - w.x) * (1.0 - w.y), w.x * (1.0 - w.y),
                 (1.0 - w.x) * w.y, w.x * w.y);
   vec4 c = c00 * a.x + c10 * a.y + c01 * a.z + c11 * a.w;
#ifdef SEAM_CENTER
   c.rgb = SEAM_CENTER + (c.rgb - SEAM_CENTER) / length(a);
#endif
   return c;
}

void main() {
   vec2 st = vUV.st;
   if (uvmode > 0.5) st = texture(sTD2DInputs[COORD_IN], vUV.st).rg;
   bool blend = uvmode < 0.5 && seamless > 0.5 && seamless < 1.5;
   fragColor = TDOutputSwizzle(blend ? _seamless(st) : _src(st));
}
