// hydra `voronoi` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: scale (5.0), speed (0.3), blending (0.3)

uniform float time;          // -> absTime.seconds
uniform float uvmode;        // -> Pipeline page, mode
uniform float seamless;      // -> Pipeline page, seamless
uniform float seamwidth;     // -> Pipeline page, seam width
uniform float scale;
uniform float speed;
uniform float blending;

#define COORD_IN 0

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 voronoi(vec2 _st, float scale, float speed, float blending) {
   vec3 color = vec3(.0);
   // Scale
   _st *= scale;
   // Tile the space
   vec2 i_st = floor(_st);
   vec2 f_st = fract(_st);
   float m_dist = 10.;  // minimun distance
   vec2 m_point;        // minimum point
   for (int j=-1; j<=1; j++ ) {
   for (int i=-1; i<=1; i++ ) {
   vec2 neighbor = vec2(float(i),float(j));
   vec2 p = i_st + neighbor;
   vec2 point = fract(sin(vec2(dot(p,vec2(127.1,311.7)),dot(p,vec2(269.5,183.3))))*43758.5453);
   point = 0.5 + 0.5*sin(time*speed + 6.2831*point);
   vec2 diff = neighbor + point - f_st;
   float dist = length(diff);
   if( dist < m_dist ) {
   m_dist = dist;
   m_point = point;
   }
   }
   }
   // Assign a color using the closest point position
   color += dot(m_point,vec2(.3,.6));
   color *= 1.0 - blending*m_dist;
   return vec4(color, 1.0);
}

float _snap(float f) {
   if (seamless < 1.5 || uvmode > 0.5) return f;
   float k = max(1.0, floor(abs(f) / 6.283185307 + 0.5));
   return (f < 0.0 ? -k : k) * 6.283185307;
}

vec4 _src(vec2 st) {
   return voronoi(st, scale, speed, blending);
}

vec4 _seamless(vec2 st) {
   vec4 c00 = _src(st);
   vec2 w = smoothstep(1.0 - max(seamwidth, 0.001), 1.0, abs(st * 2.0 - 1.0));
   if (w.x + w.y == 0.0) return c00;           // inside the band: plain hydra
   vec2 sh = fract(st + 0.5);
   vec4 c10 = _src(vec2(sh.x, st.y));
   vec4 c01 = _src(vec2(st.x, sh.y));
   vec4 c11 = _src(sh);
   vec4 a = vec4((1.0 - w.x) * (1.0 - w.y), w.x * (1.0 - w.y),
                 (1.0 - w.x) * w.y, w.x * w.y);
   vec4 c = c00 * a.x + c10 * a.y + c01 * a.z + c11 * a.w;
#ifdef SEAM_CENTER
   c.rgb = SEAM_CENTER + (c.rgb - SEAM_CENTER) / length(a);
#endif
   return c;
}

void main() {
   vec2 st = vUV.st;
   if (uvmode > 0.5) st = texture(sTD2DInputs[COORD_IN], vUV.st).rg;
   bool blend = uvmode < 0.5 && seamless > 0.5 && seamless < 1.5;
   fragColor = TDOutputSwizzle(blend ? _seamless(st) : _src(st));
}
